# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-29 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_teacher_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('px', '培训机构'), ('gr', '个人'), ('gx', '高校')], default='px', max_length=20),
        ),
    ]
